# Generated by Django 5.2 on 2025-04-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_itinerary_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload image of city', null=True, upload_to='cities/'),
        ),
    ]
