# Generated by Django 5.2 on 2025-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_city_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, help_text='RO, US ...', max_length=2, null=True, unique=True),
        ),
    ]
