# Generated by Django 5.2 on 2025-04-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_country_iso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(help_text='RO, US ...', max_length=2, unique=True),
        ),
    ]
