# Generated by Django 5.2 on 2025-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_country_iso_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='interestPoints',
            field=models.CharField(blank=True, help_text='3 interest points divided by ,', max_length=200, null=True),
        ),
    ]
